keywords:
  - scrum master
  - scrummaster
  - agile coach

sites:
  - freelance_nl
  - malt_nl
  - yacht
  - brunel
  - between
  - quest4
  - headfirst
  - striive
  - freep
  - flextender
  - tenderned

email:
  sender: ""
  password: ""
  recipient: bjorngrob1980@gmail.com
  smtp_host: smtp.gmail.com
  smtp_port: 587
